name: CD

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-491704
          install_components: 'beta'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/notely-491704/notely-ar-repo/notely:latest \
            --region=us-central1 \
            .

      - name: Run migrations
        run: npm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-491704/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-491704 \
            --max-instances=4 \
            --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }}"