name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code...
        uses: actions/checkout@v4

      - name: Setting up Node...
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: installing dependencies..
        run: npm ci

      - name: running tests...
        run: npm run test

      - name: running coverage...
        run: npm run coverage
    
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code...
        uses: actions/checkout@v4

      - name: Setting up Node...
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: installing dependencies...
        run: npm ci

      - name: Checking formatting issues...
        run: npm run format:check

      - name: fixing formatting... 
        run: npm run format:write     
      
      - name: checking linting issues...
        run:  npm run lint -- --max-warnings=0