name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies # i need vitest to run my tests, so i need 
        run: npm ci                # CI runner to install my dependencies

      - name: Run tests
        run: npm run test --coverage # coverage is the measure of how much of your code is being tested
                                     # printing it in the console in the actions tab
                                     